services:
  backend:
    container_name: backend
    image: node:22-alpine
    restart: always
    volumes: [ ./:/app ]
    working_dir: /app
    command: >
      sh -c "npm ci
      && npx --workspace=backend tsc
      && npm --workspace=backend start"

  nginx:
    container_name: nginx
    build:
      context: .
    restart: always
    working_dir: /www
    ports: [ "8443:443" ]
