services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports: [ "8443:443" ]
