#version: '3.8'

services:
  backend:
    container_name: backend
    image: node:22-alpine
    restart: always
    volumes: [ ./backend:/app ]
    working_dir: /app
    command: >
      sh -c "npm ci
      && npm run dev"

  frontend:
    container_name: frontend
    image: node:22-alpine
    restart: always
    volumes: [ ./frontend:/app ]
    ports: [ "8000:8000" ]
    working_dir: /app
    command: >
      sh -c "npm ci
      && npm run dev"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports: [ "8080:8080" ]

volumes:
  database:
