#version: '3.8'

services:
  node:
    container_name: node
    image: node:22-alpine
    networks: [ transcendence ]
    env_file: [ .env ]
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    command: >
      sh -c "npm install
      && npm update
      && npm start"

  db:
    image: postgres:alpine
    container_name: django_db
    networks: [ transcendence ]
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer
    networks: [ transcendence ]
    depends_on:
      - db
    ports:
      - "8080:8080"

networks:
  transcendence:
    driver: bridge

volumes:
  db_data:
