#version: '3.8'

services:
  backend:
    container_name: backend
    image: node:22-alpine
    restart: always
    env_file: [ .env ]
    volumes: [ ./backend:/app ]
    ports: [ "3000:3000" ]
    working_dir: /app
    command: >
      sh -c "npm install
      && npm update
      && npx tsc
      && npm run dev"

  frontend:
    container_name: frontend
    image: node:22-alpine
    restart: always
    env_file: [ .env ]
    volumes: [ ./frontend:/app ]
    ports: [ "8000:5173" ]
    working_dir: /app
    command: >
      sh -c "npm install
      && npm update
      && npm run dev"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  database:
