services:
  backend:
    container_name: backend
    image: node:22-alpine
    restart: always
    volumes: [ ./backend:/app ]
    working_dir: /app
    command: >
      sh -c "npm ci
      && npx tsc
      && npm start"

  nginx:
    container_name: nginx
    build:
      context: .
    restart: always
    working_dir: /www
    ports: [ "8443:443" ]
