CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

SELECT id, displayName, password FROM users WHERE username = 'test'
SELECT displayName, avatar FROM users WHERE id = 5.0
SELECT name2 FROM friends WHERE name1 = 'test'
SELECT * FROM games WHERE user1 = 5.0
SELECT displayName 
                              FROM users
                              WHERE id = 5.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 5.0
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

INSERT INTO users (username, displayName, email, password)
                                 SELECT 'ca', 'ca', 'ca@gmail.com', '$2b$10$b2SNBbB70w4om4Clm847teju1'/*+28 bytes*/
                                 WHERE NOT EXISTS(SELECT 1 FROM users WHERE username = 'ca' AND displayName = 'ca')
UPDATE users SET avatar = x'52494646f0e20000574542505650384ce3e200002f8fc163104d48ac6d376c9b'/*+58072 bytes*/ WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
INSERT INTO games (user1, user2, score1, score2, date) VALUES (98.0, 1.0, 0.0, 2.0, '2025-05-18')
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
INSERT INTO games (user1, user2, score1, score2, date) VALUES (98.0, 1.0, 0.0, 2.0, '2025-05-18')
SELECT displayName 
                              FROM users
                              WHERE id = 98.0

    INSERT INTO friends (name1, name2)
    SELECT 'ca', 'a'
    WHERE EXISTS (SELECT 1 FROM users WHERE displayName = 'a')
    AND NOT EXISTS (SELECT 1 FROM friends WHERE name1 = 'ca' AND name2 = 'a')
  
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
INSERT INTO games (user1, user2, score1, score2, date) VALUES (98.0, 1.0, 0.0, 2.0, '2025-05-18')
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

SELECT id, displayName, password FROM users WHERE username = 'ca'
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

SELECT id, displayName, password FROM users WHERE username = 'ca'
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

SELECT id, displayName, password FROM users WHERE username = 'ca'
INSERT INTO games (user1, user2, score1, score2, date) VALUES (98.0, 0.0, 2.0, 0.0, '2025-05-18')
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

SELECT id, displayName, password FROM users WHERE username = 'ca'
INSERT INTO games (user1, user2, score1, score2, date) VALUES (98.0, 0.0, 2.0, 0.0, '2025-05-18')
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

SELECT id, displayName, password FROM users WHERE username = 'ca'
INSERT INTO games (user1, user2, score1, score2, date) VALUES (98.0, 0.0, 1.0, 2.0, '2025-05-18')
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
INSERT INTO users (username, displayName, email, password)
                                 SELECT 'a', 'a', 'ca@gmail.com', '$2b$10$g189FpvycLkDZxwsERWrDeff4'/*+28 bytes*/
                                 WHERE NOT EXISTS(SELECT 1 FROM users WHERE username = 'a' AND displayName = 'a')
UPDATE users SET avatar = x'52494646f0e20000574542505650384ce3e200002f8fc163104d48ac6d376c9b'/*+58072 bytes*/ WHERE username = 'a'
SELECT displayName, avatar FROM users WHERE id = 128.0
SELECT name2 FROM friends WHERE name1 = 'a'
SELECT * FROM games WHERE user1 = 128.0
SELECT displayName 
                              FROM users
                              WHERE id = 128.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 128.0
SELECT displayName 
                              FROM users
                              WHERE id = 128.0

    INSERT INTO friends (name1, name2)
    SELECT 'a', 'ca'
    WHERE EXISTS (SELECT 1 FROM users WHERE displayName = 'ca')
    AND NOT EXISTS (SELECT 1 FROM friends WHERE name1 = 'a' AND name2 = 'ca')
  
SELECT displayName, avatar FROM users WHERE id = 128.0
SELECT name2 FROM friends WHERE name1 = 'a'
SELECT * FROM games WHERE user1 = 128.0
SELECT displayName 
                              FROM users
                              WHERE id = 128.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 128.0
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0

    INSERT INTO friends (name1, name2)
    SELECT 'ca', 'a'
    WHERE EXISTS (SELECT 1 FROM users WHERE displayName = 'a')
    AND NOT EXISTS (SELECT 1 FROM friends WHERE name1 = 'ca' AND name2 = 'a')
  
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT id, displayName, password FROM users WHERE username = 'a'
SELECT displayName, avatar FROM users WHERE id = 128.0
SELECT name2 FROM friends WHERE name1 = 'a'
SELECT * FROM games WHERE user1 = 128.0
SELECT displayName 
                              FROM users
                              WHERE id = 128.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 128.0
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, displayName TEXT, email TEXT, password TEXT, avatar BLOB)
CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER, user2 INTEGER, score1 INTEGER, score2 INTEGER, date DATE)
CREATE TABLE IF NOT EXISTS friends (id INTEGER PRIMARY KEY AUTOINCREMENT, name1 TEXT, name2 TEXT, UNIQUE(name1, name2))

  INSERT OR IGNORE INTO users (username, displayName, password, avatar)
  VALUES ('LOCAL', 'AI', '', NULL)

SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
DELETE FROM friends WHERE name1 = 'ca' AND name2 = 'a'
SELECT displayName 
                              FROM users
                              WHERE id = 98.0

    INSERT INTO friends (name1, name2)
    SELECT 'ca', 'a'
    WHERE EXISTS (SELECT 1 FROM users WHERE displayName = 'a')
    AND NOT EXISTS (SELECT 1 FROM friends WHERE name1 = 'ca' AND name2 = 'a')
  
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
SELECT id, displayName, password FROM users WHERE username = 'a'
SELECT displayName, avatar FROM users WHERE id = 128.0
SELECT name2 FROM friends WHERE name1 = 'a'
SELECT * FROM games WHERE user1 = 128.0
SELECT displayName 
                              FROM users
                              WHERE id = 128.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 128.0
SELECT id, displayName, password FROM users WHERE username = 'ca'
SELECT displayName, avatar FROM users WHERE id = 98.0
SELECT name2 FROM friends WHERE name1 = 'ca'
SELECT * FROM games WHERE user1 = 98.0
SELECT displayName 
                              FROM users
                              WHERE id = 98.0
SELECT users.displayName 
                              FROM games 
                              JOIN users ON 1 = users.id 
                              WHERE games.user1 = 98.0
