services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    volumes: [ ./backend/database:/app/backend/database ]

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports: [ "8443:443" ]
